FROM alpine:latest

RUN apk update && \
    apk add --no-cache \
    restic \
    borgbackup \
    neovim \
    fish \
    curl \
    openssh-client \
    git \
    && rm -rf /var/cache/apk/*

# Set Fish as the default shell
ENV SHELL /usr/bin/fish

WORKDIR /

RUN echo "umask 022" >> /etc/profile
#RUN chmod 700 /root/.ssh/

# Command to run on container start
CMD ["fish"]