# Start with the Alpine base image
FROM alpine:latest

# Set environment variables for non-interactive installations
ENV TERM xterm

# Install required packages
RUN apk update && \
    apk add --no-cache \
    restic \
    borgbackup \
    neovim \
    fish \
    curl \
    openssh-client \
    git \
    && rm -rf /var/cache/apk/*

# Set Fish as the default shell
ENV SHELL /usr/bin/fish
RUN chsh -s /usr/bin/fish

# Set up the working directory
WORKDIR /root

# Command to run on container start
CMD ["fish"]