FROM alpine:latest

RUN apk update && \
    apk add --no-cache \
    restic \
    borgbackup \
    neovim \
    fish \
    curl \
    openssh-client \
    git \
    && rm -rf /var/cache/apk/*

# Set Fish as the default shell
ENV SHELL /usr/bin/fish
RUN chsh -s /usr/bin/fish

WORKDIR /

# Command to run on container start
CMD ["fish"]