apiVersion: apps/v1
kind: Deployment
metadata:
  name: unbound
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: unbound
  template:
    metadata:
      labels:
        app: unbound
    spec:
      containers:
      - name: unbound  
        image: mvance/unbound:latest@sha256:4bf67b567f392956455bd4f8a4cdd48010e234f1a07c0a99c2cff2ddbb3e8a7a
        volumeMounts:
        - mountPath: /opt/unbound/etc/unbound/unbound.conf
          name: unbound-config
          subPath: unbound.conf
      volumes:
      - configMap:
          defaultMode: 420
          name: unbound-config
        name: unbound-config
