name: Test Runner

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: zero2

    steps:
      - name: Checkout code
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4

      - run: echo "Hello World"
